# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

assetic:
    bundles:
        - CampaignChainHookDueBundle
    assets:
        clockpicker_js:
            inputs:
                - "@CampaignChainHookDueBundle/Resources/public/components/clockpicker/dist/bootstrap-clockpicker.min.js"
        clockpicker_css:
            inputs:
                - "@CampaignChainHookDueBundle/Resources/public/components/clockpicker/dist/bootstrap-clockpicker.min.css"
twig:
    form:
        resources:
            - 'CampaignChainHookDueBundle:Form:fields.html.twig'
sp_bower:
    bundles:
        CampaignChainHookDueBundle: null