# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    campaignchain.hook.campaignchain.due:
        class: CampaignChain\Hook\DueBundle\EntityService\DueService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.hook.form.type.campaignchain.due:
        class: CampaignChain\Hook\DueBundle\Form\Type\DueType
        arguments: [ @service_container ]
    campaignchain.hook.listener.campaignchain.due:
        class: CampaignChain\Hook\DueBundle\EventListener\DueListener
        arguments: [ @service_container ]